config/routes.rb
Etote::Application.routes.draw do

  resources :categories do
    resources :documents, :shallow => true
  end

  namespace :api do
    root :to => 'api_root#index'
    namespace :v1 do
      root :to => 'root#index'
      resources :categories, :only => :index
      resources :totes, :only => :create
      match 'report' => 'totes#index', :via => :get
    end
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :category
  has_many :document_requests

  attr_accessible :name, :url

  validates :name, :url, :category, :presence => true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :find_category, :only => [:new, :create]

  def show
    @document = Document.find(params[:id])
  end

  def new
    @document = Document.new
    @document.category = @category
  end

  def edit
    @document = Document.find(params[:id])
  end

  def create
    @document = Document.new(params[:document])
    @document.category = @category
    if @document.save
      redirect_to @document, notice: 'Document was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @document = Document.find(params[:id])
    if @document.update_attributes(params[:document])
      redirect_to @document, notice: 'Document was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to category_path(@document.category), notice: 'Document deleted.'
  end

  private
  def find_category
    @category = Category.find(params[:category_id])
  end
end

app/views/documents/_form.html.erb
<%= form_for(@category ? [@category, @document] : @document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <p>
    <b>Category:</b>
    <%= @document.category.name %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Edit Document</h1>

<%= render 'form' %>

<%= link_to 'Back', document_path(@document) %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', category_path(@category) %>

app/views/documents/show.html.erb
<h1>Document Details</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @document.name %>
</p>

<p>
  <b>Url:</b>
  <%= @document.url %>
</p>

<p>
  <b>Category:</b>
  <%= @document.category.name %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Delete', @document, confirm: 'Are you sure?', method: :delete %> |
<%= link_to 'Back', category_path(@document.category) %>