config/routes.rb
Etote::Application.routes.draw do

  resources :categories do
    resources :documents, :shallow => true
  end

  namespace :api do
    root :to => 'api_root#index'
    namespace :v1 do
      root :to => 'root#index'
      resources :categories, :only => :index
      resources :totes, :only => :create
      match 'report' => 'totes#index', :via => :get
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :image_url
  has_many :documents

  validates :name, :presence => true
end

app/controllers/api/v1/categories_controller.rb
module Api::V1
  class CategoriesController < ApiController
    def index
      @categories = Category.all(:include => :documents)
      render :json => @categories
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_url, notice: 'Category deleted.'
  end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<p id="notice"><%= notice %></p>
<ul>
  <% @categories.each do |category| %>
    <li>
      <%= category.name %>
      <%= link_to "Details", category_path(category) %>
      <%= link_to "Edit", edit_category_path(category) %>
      <%= link_to 'Delete', category, confirm: 'Are you sure?', method: :delete %>
    </li>
  <% end %>
</ul>
<%= link_to "New", new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1>Category Details</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Image:</b>
  <%= @category.image_url %>
</p>

<h2>Documents</h2>
<ul>
  <% @category.documents.each do |doc| %>
    <li>
      <%= link_to doc.name, document_path(doc) %>
    </li>
  <% end %>
  <li><%= link_to "Add New Document...", new_category_document_path(@category) %></li>
</ul>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>